site: Lawrence Ypil

url: https://lawrenceypil.com
baseurl: 

collections:
  pages:
    output: true
    permalink: :name
  posts:
    output: true
    permalink: /selected-works/:slug

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap

pagination:
    enabled: true
paginate: 5
paginate_path: "/selected-works/page:num/"