basic_settings:
  site_title: Lawrence Ypil
  site_tagline: 
  favicon_image:

header_settings:
  logo_image: 
  logo_width: 200
  overlay_opacity: 0.7

menu_settings:
  menu_items:
    - title: 'About'
      url: '/about/'
    - title: 'Publications'
      url: '/publications/'
    - title: 'Events'
      url: '/events/'
    - title: 'Interviews'
      url: '/interviews/'
    - title: 'Dog Ears'
      url: '/dog-ears/'
    - title: 'Contact'
      url: '/contact/'


grid_settings:
  grid_spacing: 10

contact_settings:
  form_action: ''
  confirmation_url: 
  email_subject: 
  send_button_text: 

social_settings:
  facebook_url: ''
  twitter_url: ''
  instagram_url: 'https://www.instagram.com/lawrenceypil/'
  snapchat_url: ''
  youtube_url: ''
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: 'https://www.amazon.com/Experiment-Tropics-Lawrence-Lacambra-Ypil/dp/0982814259'
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  deviantart_url: ''
  github_url: ''
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''
  linkedin_url: ''

color_settings:
  background_color: '#fdfbf1'
  background_alt_color: '#fdfbf3'
  text_dark_color: '#08090a'
  text_medium_color: '#222223'
  text_light_color: '#ABB7B7'
  accent_color: '#B4D5FE'
  border_color: '#dddddd'
  overlay_background_color: '#161B21'
  overlay_text_color: '#ABB7B7'
  error_color: '#02479d'

font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css2?family=Merriweather:wght@300;400&family=Open+Sans:ital,wght@0,400;0,600;1,400;1,600&display=swap" rel="stylesheet">'
  title_font: '"Merriweather", serif'
  body_font: '"Open Sans", sans-serif'
  regular_weight: 400
  bold_weight: 600
  site_title:
    small_size: 25
    medium_size: 30
    large_size: 35
    weight: 400
    letter_spacing: 0
  site_tagline:
    small_size: 16
    medium_size: 17
    large_size: 18
    weight: 400
    letter_spacing: 0
    line_height: 1.5
  menu:
    small_size: 30
    medium_size: 17
    large_size: 18
    weight: 400
    letter_spacing: 0
  h1:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 400
    letter_spacing: -0.02
    line_height: 1.2
  h2:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 400
    letter_spacing: -0.02
    line_height: 1.2
  h3:
    small_size: 22
    medium_size: 25
    large_size: 30
    weight: 400
    letter_spacing: -0.02
    line_height: 1.3
  h4:
    small_size: 17
    medium_size: 22
    large_size: 22
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 12
    medium_size: 14
    large_size: 16
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 16
    medium_size: 18
    large_size: 20
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  blockquote:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 400
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 600
    letter_spacing: 0

advanced_settings:
  ajax_loading: true
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""